version: "3"
services:
  app:
    image: client_la_liga
    ports:
      - 3000:3000
    restart: unless-stopped
    links:
      - api
    command: yarn start
  api:
    image: server_la_liga
    env_file: ./server/docker-compose.env
    ports:
      - 8001:8000
    restart: unless-stopped
